#!/usr/bin/env python3
"""Generate documentation for all canonical color tokens."""

from pathlib import Path

if __package__:
    from .token_resolver import load_token_documents
else:
    from token_resolver import load_token_documents

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/TOKENS.md"


def flatten_tokens(values, prefix=""):
    """Yield dotted token names and scalar values in source order.

    Args:
        values: Nested token mapping.
        prefix: Optional path prepended to yielded token names.

    Yields:
        Pairs containing each scalar token path and value.
    """
    for name, value in values.items():
        token_name = f"{prefix}.{name}" if prefix else name
        if isinstance(value, dict):
            yield from flatten_tokens(value, token_name)
        else:
            yield token_name, value


def token_table(namespace, values):
    """Build a Markdown table for one resolved token namespace.

    Args:
        namespace: Namespace prepended to each token path.
        values: Nested resolved token mapping.

    Returns:
        Markdown table lines.
    """
    rows = ["| Token | Value |", "| --- | --- |"]
    rows.extend(
        f"| `{namespace}.{name}` | `{value}` |"
        for name, value in flatten_tokens(values)
    )
    return rows


def build_report(tokens):
    """Build the generated Markdown reference for canonical color tokens.

    Args:
        tokens: Resolved documents keyed by namespace.

    Returns:
        Complete Markdown document text.
    """
    return "\n".join(
        [
            "# Color Tokens",
            "",
            "<!-- Generated by scripts/generate_token_docs.py. Do not edit manually. -->",
            "",
            "Values are resolved from the canonical files in `tokens/`.",
            "",
            "## Colors",
            "",
            *token_table("colors", tokens["colors"]),
            "",
        ]
    )


def main():
    """Load project tokens and write the Markdown token reference."""
    tokens = load_token_documents(ROOT / "tokens")
    OUT.write_text(build_report(tokens), encoding="utf-8", newline="\n")
    print(OUT)


if __name__ == "__main__":
    main()
